package routes

import (
	singlechat "homegpt/backend/features/single_chat/routes"

	_ "homegpt/docs" // docs is generated by swag init

	fiberSwagger "github.com/swaggo/fiber-swagger"

	"github.com/gofiber/fiber/v2"
)

func RegisterRoutes(app *fiber.App) {

	//if root then redirect to swagger

	app.Get("/", func(c *fiber.Ctx) error {
		return c.Redirect("/swagger/index.html", fiber.StatusFound)
	})
	app.Get("/swagger/*", fiberSwagger.WrapHandler)

	singlechat.RegisterSingleChatRoutes(app)
	// Add more routes as needed
}
